# Generated by Django 5.1.4 on 2024-12-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.BinaryField()),
                ('featured_columns', models.JSONField()),
                ('label_encoders', models.BinaryField(blank=True, null=True)),
                ('scaler', models.BinaryField(blank=True, null=True)),
                ('result', models.BinaryField(blank=True, null=True)),
                ('trained_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
